######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 26 23:01:23 2012
######################################################################

TEMPLATE= app
TARGET = FF7tkDemo

QT       += core gui xml
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Input
HEADERS +=  mainwindow.h \
	    static_data/FF7Item.h \
	    static_data/FF7Location.h \
	    static_data/FF7Materia.h \
	    static_data/FF7Save.h \
	    static_data/FF7Save_Const.h \
	    static_data/FF7Save_Types.h \
	    static_data/FF7Text.h \
	    static_data/SaveIcon.h \
	    static_data/icons/Materia_Icons/command.xpm \
	    static_data/icons/Materia_Icons/magic.xpm \
	    static_data/icons/Materia_Icons/summon.xpm \
	    static_data/icons/Materia_Icons/support.xpm \
	    static_data/icons/Materia_Icons/independent.xpm \
	    static_data/icons/Materia_Icons/command_star_empty.xpm \
	    static_data/icons/Materia_Icons/magic_star_empty.xpm \
	    static_data/icons/Materia_Icons/summon_star_empty.xpm \
	    static_data/icons/Materia_Icons/support_star_empty.xpm \
	    static_data/icons/Materia_Icons/independent_star_empty.xpm \
	    static_data/icons/Materia_Icons/command_star_full.xpm \
	    static_data/icons/Materia_Icons/magic_star_full.xpm \
	    static_data/icons/Materia_Icons/summon_star_full.xpm \
	    static_data/icons/Materia_Icons/support_star_full.xpm \
	    static_data/icons/Materia_Icons/independent_star_full.xpm \
	    static_data/icons/Item_Icons/accessory.xpm \
	    static_data/icons/Item_Icons/armor.xpm \
	    static_data/icons/Item_Icons/clip.xpm \
	    static_data/icons/Item_Icons/glove.xpm \
	    static_data/icons/Item_Icons/gun.xpm \
	    static_data/icons/Item_Icons/gunarm.xpm \
	    static_data/icons/Item_Icons/item.xpm \
	    static_data/icons/Item_Icons/mphone.xpm \
	    static_data/icons/Item_Icons/spear.xpm \
	    static_data/icons/Item_Icons/staff.xpm \
	    static_data/icons/Item_Icons/star.xpm \
	    static_data/icons/Item_Icons/sword.xpm \
	    static_data/icons/Item_Icons/mlink.xpm \
	    static_data/icons/Item_Icons/m_no_grow_slot.xpm \
	    static_data/icons/Item_Icons/m_grow_slot.xpm \
	    static_data/icons/Materia_Icons/all.xpm \
	    static_data/FF7Char.h \
	    static_data/Type_FF7CHAR.h \
	    static_data/Type_materia.h \
	    utils/LZS.h \
	    widgets/SlotPreview.h \
	    widgets/MateriaEditor.h \
	    widgets/ItemPreview.h \
	    widgets/DialogPreview.h \
	    widgets/SlotSelect.h \
	    widgets/ChocoboEditor.h \
	    widgets/ItemSelector.h \
	    widgets/ItemList.h \
	    widgets/CharEditor.h \
	    widgets/MetadataCreator.h \
	    widgets/DoubleCheckBox.h \
	    widgets/PhsListWidget.h \
	    widgets/MenuListWidget.h \
    utils/Lgp_p.h \
    utils/Lgp.h \
    widgets/OptionsWidget.h
FORMS += mainwindow.ui
SOURCES += main.cpp \
           mainwindow.cpp \
           static_data/FF7Item.cpp \
           static_data/FF7Location.cpp \
           static_data/FF7Materia.cpp \
           static_data/FF7Save.cpp \
           static_data/FF7Text.cpp \
           widgets/DialogPreview.cpp \
           widgets/ItemPreview.cpp \
           widgets/MateriaEditor.cpp \
           widgets/SlotPreview.cpp \
    static_data/FF7Char.cpp \
    widgets/CharEditor.cpp \
    widgets/SlotSelect.cpp \
    static_data/SaveIcon.cpp \
    widgets/ChocoboEditor.cpp \
    widgets/ItemSelector.cpp \
    widgets/ItemList.cpp \
    widgets/MetadataCreator.cpp \
    utils/LZS.cpp \
    widgets/DoubleCheckBox.cpp \
    widgets/PhsListWidget.cpp \
    widgets/MenuListWidget.cpp \
    utils/Lgp_p.cpp \
    utils/Lgp.cpp \
    widgets/OptionsWidget.cpp
